I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script
    $ renpy.movie_cutscene("Dramatic.webm")
  File "game/script.rpy", line 39, in <module>
    $ renpy.movie_cutscene("Dramatic.webm")
IOError: Couldn't find file 'Dramatic.webm'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script
    $ renpy.movie_cutscene("Dramatic.webm")
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 39, in <module>
    $ renpy.movie_cutscene("Dramatic.webm")
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\exports.py", line 1538, in movie_cutscene
    roll_forward=roll_forward)
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\display\core.py", line 3380, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\audio\audio.py", line 1060, in periodic
    six.reraise(exc[0], exc[1], exc[2])
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\audio\audio.py", line 1038, in periodic_thread_main
    periodic_pass()
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\audio\audio.py", line 979, in periodic_pass
    c.periodic()
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\audio\audio.py", line 457, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\audio\audio.py", line 73, in load
    rv = renpy.loader.load(fn)
  File "C:\Program Files (x86)\renpy-7.3.5-sdk\renpy\loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'Dramatic.webm'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Research Artefact 1.0
Wed Apr 01 14:45:06 2020
